languageCode = "hi"
languageName = "हिन्दी"
weight = 2
title = "फ़ार्मफ्रंटियर्स"
contentDir = "content"

[params]
  displayName = "HI"
  isoCode = "hi"
  rtl = false
  #logo = "img/avatar.png"
  description = "फ़ार्मफ्रंटियर्स कृषि नवाचार में नवीनतम जानकारी का आपका गेटवे है। आधुनिक खेती तकनीकों, सतत प्रथाओं, और तकनीकी प्रगति पर ध्यान केंद्रित करने के साथ, हम कृषि के नए युग का पता लगाने के लिए समर्पित हैं। हमारा प्लेटफ़ॉर्म किसानों और कृषि व्यवसायों के लिए उत्पादकता बढ़ाने और अत्याधुनिक तकनीक अपनाने के लिए गहन लेख, विशेषज्ञ अंतर्दृष्टि, और व्यावहारिक समाधान प्रदान करता है।"
  # copyright = "कॉपी, _राइट?_ :thinking_face:"
  dateFormat = "2 जनवरी 2006"

[author]
  name = "फ़ार्मफ्रंटियर्स"
  image = "img/avatar.png"
  headline = "कृषि के नए युग की खोज"
  bio = "फ़ार्मफ्रंटियर्स आपके लिए सतत कृषि, उन्नत खेती तकनीकों, और आज के किसानों के लिए व्यावहारिक समाधानों पर अंतर्दृष्टि का प्रमुख स्रोत है।"
  links = [
     { link = "https://your_domain.com" },  # अपने डोमेन के साथ बदलें
     { github = "https://github.com/your_github" },  # अपने GitHub के साथ बदलें
     { x-twitter = "https://twitter.com/your_twitter" }  # अपने Twitter के साथ बदलें
   ]
