# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 9

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Categories"
  weight = 20

[[main]]
  name = "Latest Posts"
  parent = "Categories"
  pageRef = "tags/posts"
  weight = 20

[[main]]
  name = "Technology"
  parent = "Categories"
  pageRef = "tags/technology"
  weight = 20

[[main]]
  name = "Modern Solutions"
  parent = "Categories"
  pageRef = "tags/modern-solutions"
  weight = 20

[[main]]
  name = "Machineries"
  parent = "Categories"
  pageRef = "tags/Machineries"
  weight = 20  

  [[main]]
  name = "About Us"
  pageRef = "about"
  weight = 21

[[main]]
  identifier = "Youtube"
  pre = "youtube"
  url = "https://m.youtube.com"
  weight = 40

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/FarmFrontiers"
  weight = 60

[[main]]
  identifier = "Whatsapp"
  pre = "Whatsapp"
  url = "https://x.com/FarmFrontiers"
  weight = 61 

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://x.com/FarmFrontiers"
  weight = 61

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10
